services:
#    pello_inventory.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    inventory.security.sha1_password_encoder:
        class: ApiBundle\Security\Encoder\Sha1PasswordEncoder
    
    pello_inventory.dao.item:
         class: ApiBundle\Service\DAO\ItemDAO
         arguments: ['ApiBundle:Item', '@doctrine.orm.entity_manager' ]

    pello_inventory.bo.item:
         class: ApiBundle\Service\Business\ItemBusiness
         arguments: ['@pello_inventory.dao.item']
