services:
#    api_inventory.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    inventory.security.sha1_password_encoder:
        class: ApiBundle\Security\Encoder\Sha1PasswordEncoder
    
    api_inventory.dao.item:
         class: ApiBundle\Service\DAO\ItemDAO
         arguments: ['ApiBundle:Item', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.item:
         class: ApiBundle\Service\Business\ItemBusiness
         arguments: ['@api_inventory.dao.item']

    api_inventory.dao.class:
         class: ApiBundle\Service\DAO\ClassDAO
         arguments: ['ApiBundle:AClass', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.class:
         class: ApiBundle\Service\Business\ClassBusiness
         arguments: ['@api_inventory.dao.class']

    api_inventory.dao.meetup:
        class: ApiBundle\Service\DAO\MeetupDAO
        arguments: ['ApiBundle:Meetup', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.meetup:
        class: ApiBundle\Service\Business\MeetupBusiness
        arguments: ['@api_inventory.dao.meetup']

    api_inventory.dao.event:
         class: ApiBundle\Service\DAO\EventDAO
         arguments: ['ApiBundle:Event', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.event:
         class: ApiBundle\Service\Business\EventBusiness
         arguments: ['@api_inventory.dao.event']

    api_inventory.dao.beat:
         class: ApiBundle\Service\DAO\BeatDAO
         arguments: ['ApiBundle:Beat', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.beat:
         class: ApiBundle\Service\Business\BeatBusiness
         arguments: ['@api_inventory.dao.beat']

    api_inventory.dao.idea:
         class: ApiBundle\Service\DAO\IdeaDAO
         arguments: ['ApiBundle:Idea', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.idea:
         class: ApiBundle\Service\Business\IdeaBusiness
         arguments: ['@api_inventory.dao.idea']

    api_inventory.dao.chatgroup:
         class: ApiBundle\Service\DAO\ChatGroupDAO
         arguments: ['ApiBundle:ChatGroup', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.chatgroup:
         class: ApiBundle\Service\Business\ChatGroupBusiness
         arguments: ['@api_inventory.dao.chatgroup']

    api_inventory.dao.message:
         class: ApiBundle\Service\DAO\MessageDAO
         arguments: ['ApiBundle:Message', '@doctrine.orm.entity_manager' ]

    api_inventory.bo.message:
         class: ApiBundle\Service\Business\MessageBusiness
         arguments: ['@api_inventory.dao.message']